# Generated by Django 4.2.5 on 2023-09-13 08:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social_application", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reaction",
            unique_together=set(),
        ),
    ]
