# Generated by Django 4.2.5 on 2023-09-11 15:55

from django.db import migrations, models
import phonenumber_field.modelfields
import social_application.models


class Migration(migrations.Migration):
    dependencies = [
        ("social_application", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                related_name="following_profiles",
                to="social_application.follow",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="followings",
            field=models.ManyToManyField(
                blank=True,
                related_name="follower_profiles",
                to="social_application.follow",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=social_application.models.profile_image_file_path,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="posts",
            field=models.ManyToManyField(
                blank=True, related_name="profiles", to="social_application.post"
            ),
        ),
    ]
