# Generated by Django 4.2.5 on 2023-09-18 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social_application", "0002_alter_reaction_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reaction",
            old_name="user",
            new_name="author",
        ),
    ]
