# Generated by Django 4.2.5 on 2023-09-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "social_application",
            "0003_alter_profile_followers_alter_profile_followings_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="comments",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="social_application.comment"
            ),
        ),
    ]
