# Generated by Django 4.2.5 on 2023-09-11 16:00

from django.db import migrations, models
import social_application.models


class Migration(migrations.Migration):
    dependencies = [
        ("social_application", "0004_alter_post_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=social_application.models.post_image_file_path,
            ),
        ),
    ]
