# Generated by Django 4.2.5 on 2023-09-11 16:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("social_application", "0005_alter_post_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["nickname"]},
        ),
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("follower", "following")},
        ),
        migrations.AlterUniqueTogether(
            name="reaction",
            unique_together={("user", "post")},
        ),
    ]
