# Generated by Django 4.2.5 on 2023-09-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_user_avatar_userfollowing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=64),
        ),
    ]
